### ISSUE TITLE
MagicMirror module shows "Lade..."

### ISSUE THREAD

**Issue by tommek83** [fhinder/MMM-Covid19-Vaccination#1]
When I start MagicMirror, the module only shows "Lade...". No data is displayed. 

Probably something with the api? I don't know how to fix it. 

Btw: Same issue with the MMM-RKI-Covid19 module.

**Comment by tommek83** [comment]
I don't know what I did, but it's working now....

**Comment by fhinder** [comment]
Hello tommek83,

thanks for the feedback. 

I think the problem is, that the initial load of the data from the API is done after the time period reloaddata is elapsed the first time.

I will consider this problem in one of the next updates.

**Comment by tommek83** [comment]
Okay, thanks for the feedback.
