### ISSUE TITLE
values are not updated

### ISSUE THREAD

**Issue by forGMB** [fhinder/MMM-Covid19-Vaccination#3]
Great module, I like it, but it looks like that latest values from 'morgenpost' are from 6th of April.
https://impfdashboard.de/daten shows current data, and there's a dataset including Bundesländer, too.
Is there a chance to switch to this as a new datasource?
data is like:
code	vaccinationsTotal	peopleFirstTotal	peopleFullTotal
DE-BW	2559741	1867730	692011
DE-BY	3232545	2359534	873011
..
BR

**Comment by fhinder** [comment]
Hello @forGMB ,

I realized,that the source is not updating. I'm working on a solution with a different data source, as suggested by you.

**Comment by fhinder** [comment]
@forGMB: The issue is solved with commit https://github.com/fhinder/MMM-Covid19-Vaccination/commit/4764af58b9c0d61abdf273902c6f6592ff14b5d6

**Comment by forGMB** [comment]
Thanks,
solution works fine, thanks for fast solving.

Small point: in README.md - default config, section data source should
be ended with ',' to get a valid config, I guess.

percentage:true, dataSource:"BMG",
states:[

BR

Am 18.04.2021 um 20:42 schrieb fhinder:

**Comment by fhinder** [comment]
You're right, readme is updated 👍
